version: '3'

services:
    marrera_django:
        container_name: marrera_django
        build: .
        command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - ./media:/code/media