version: '3'

services:
    marrera_django:
        container_name: marrera_django
        build: .
        command: bash -c "gunicorn --config gunicorn_config.py main.wsgi:application"
        ports:
            - "8000:8000"
        volumes:
            - ./media:/code/media