# Generated by Django 4.2.10 on 2025-02-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('groupid', models.CharField(max_length=99)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancegroup', to='whatsapp.whatsapp')),
            ],
        ),
    ]
