# Generated by Django 4.2.10 on 2025-03-03 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp', '0002_instancegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instance', models.CharField(max_length=99)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('1', 'Mensagem enviada'), ('2', 'Mensagem não enviada')], max_length=100)),
                ('mensagem', models.TextField(null=True)),
                ('log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msginstances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
