# Generated by Django 4.2.10 on 2024-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externaluser', '0002_remove_perfil_whatsapp_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='celular',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
