# Generated by Django 4.2.10 on 2024-03-09 22:08

from django.db import migrations, models
import externaluser.models


class Migration(migrations.Migration):

    dependencies = [
        ('externaluser', '0004_remove_perfil_datacadastro_perfil_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cobrefacil_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vencimento',
            field=models.DateTimeField(default=externaluser.models.tree_day_hence),
        ),
    ]
