# Generated by Django 4.2.10 on 2024-03-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externaluser', '0007_plano_remove_perfil_price_alter_perfil_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='plano',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='externaluser.plano'),
        ),
    ]
