# Generated by Django 4.2.10 on 2024-03-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externaluser', '0011_fatura_gerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura_gerada',
            name='due_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fatura_gerada',
            name='id_fatura',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fatura_gerada',
            name='payable_with',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fatura_gerada',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fatura_gerada',
            name='status_fatura',
            field=models.CharField(default='processing', max_length=50, null=True),
        ),
    ]
