# Generated by Django 4.2.10 on 2024-03-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externaluser', '0013_alter_perfil_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cpf_or_cnpj',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf_cnpj',
            field=models.CharField(choices=[('1', 'CPF'), ('2', 'CNPJ')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='externaluser.plano'),
        ),
    ]
