# Generated by Django 4.2.10 on 2024-03-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=15, null=True, unique=True)),
                ('cpf_cnpj', models.CharField(choices=[('1', 'CPF'), ('2', 'CNPJ')], max_length=20, null=True, unique=True)),
                ('plano', models.CharField(choices=[('1', 'Essencial - R$ 79.90 (1 instância(s))'), ('2', 'Intermediário - R$ 149.90 (2 instância(s))'), ('3', 'Avançado - R$ 299.90 (5 instância(s))'), ('4', 'Corporativo R$ 499,90 (10 instância(s))')], max_length=40, null=True)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('descricaoEndereco', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=15, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('bairro', models.CharField(max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('dataCadastro', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
