# Generated by Django 4.2.10 on 2024-03-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externaluser', '0008_alter_perfil_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='plano',
            field=models.CharField(choices=[('1', 'Essencial - R$ 79.90 (1 instância(s))'), ('2', 'Intermediário - R$ 149.90 (2 instância(s))'), ('3', 'Avançado - R$ 299.90 (5 instância(s))'), ('4', 'Corporativo R$ 499,90 (10 instância(s))')], max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='plano',
        ),
    ]
