# Generated by Django 4.2.10 on 2024-03-10 14:32

from django.db import migrations, models
import main.apps.externaluser.models


class Migration(migrations.Migration):

    dependencies = [
        ('externaluser', '0012_fatura_gerada_due_date_fatura_gerada_id_fatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='vencimento',
            field=models.DateField(default=main.apps.externaluser.models.tree_day_hence),
        ),
    ]
